# Generated by Django 5.2.15 on 2026-06-29 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarDealer',
            fields=[
                ('dealer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('st', models.CharField(blank=True, max_length=50)),
                ('lat', models.FloatField(default=0.0)),
                ('long', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('car_type', models.CharField(choices=[('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('WAGON', 'Wagon'), ('COUPE', 'Coupe'), ('HATCHBACK', 'Hatchback'), ('CONVERTIBLE', 'Convertible'), ('TRUCK', 'Truck'), ('VAN', 'Van')], max_length=20)),
                ('year', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carmodels', to='dealership.carmake')),
            ],
        ),
        migrations.CreateModel(
            name='DealerReview',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('purchase', models.BooleanField(default=False)),
                ('review', models.TextField()),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('car_make', models.CharField(blank=True, max_length=100)),
                ('car_model', models.CharField(blank=True, max_length=100)),
                ('car_year', models.IntegerField(blank=True, null=True)),
                ('sentiment', models.CharField(blank=True, max_length=20)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='dealership.cardealer')),
            ],
        ),
    ]
